### ISSUE TITLE
Probleme mit dem An und Ausschalten des Motors

### ISSUE THREAD

**Issue by karlupo** [Musiker15/msk_enginetoggle#13]
Wenn man den Motor während man fährt ausschalten und dann wieder einschaltet kann man nicht mehr fahren, Wenn man den Motor anlässt, aussteigt und dann wieder einsteigt, ist der Motor nicht an und man kann ihn auch nicht starten.

**Comment by Musiker15** [comment]
Funktioniert alles. Ich kann da keine Fehler diesbezüglich feststellen.
