### ISSUE TITLE
Crash on Lockpicking Vehicle

### ISSUE THREAD

**Issue by FuzeVTeam** [Musiker15/msk_enginetoggle#16]
I think you didnt fixed it, ill crash when i lockpick a vehicle. 

I stand in front of the vehicle, Press use on lockpick and freeze - crash

**Comment by Musiker15** [comment]
I tested it a few secondsa go and my game doesn't crash when I lockpick a vehicle.

**Comment by Musiker15** [comment]
Set `liveCoords = false` on `Config.SafetyStages`

This is just a quick fix. I'm working on a Fix.

**Comment by FuzeVTeam** [comment]
So it crashes? Was trying it over and over and crashed everytime

**Comment by Musiker15** [comment]
Bug was fixed with latest update
