### ISSUE TITLE
Engine key and command not working after update v2.8

### ISSUE THREAD

**Issue by iHemeda** [Musiker15/msk_enginetoggle#2]
i think there is an issue with Engine key and command, it`s not working with me after update v2.8 !!
did you testing it before realese ?

and why you changed `(GetPlayerPed(-1))` to `playerPed`

**Comment by iHemeda** [comment]
Only work if i restart script

**Comment by iHemeda** [comment]
try to delete line (2) : `local playerPed = PlayerPedId()` 
and rename `playerPed` to `GetPlayerPed(-1)` it will be fix this issue

i tested it and it works with me on update v2.8

**Comment by Musiker15** [comment]
Released an update
