### ISSUE TITLE
Ped id are never updated after

### ISSUE THREAD

**Issue by iSentrie** [Musiker15/msk_enginetoggle#3]
This will cause issues, a lot of them:

https://github.com/Musiker15/EngineToggle/blob/4f850c445f08eee56829ea972bd1b8f2a54bcf75/client.lua#L2

Read my comment here:

https://github.com/Musiker15/EngineToggle/commit/4f850c445f08eee56829ea972bd1b8f2a54bcf75#r63128311

**Comment by iHemeda** [comment]
try to delete line (2) : `local playerPed = PlayerPedId()`
and rename `playerPed` to `GetPlayerPed(-1)` it will be fix this issue

**Comment by Musiker15** [comment]
Released an update
