### ISSUE TITLE
Vehicles Respawn instant with "Advanced Parking" by Kiminaze

### ISSUE THREAD

**Issue by LimnedMoon** [Musiker15/msk_enginetoggle#5]
If i use this fantastic little script, every Vehicle respawns when i put into garage 
i use this in Addition with

-VehicleKeyChain by Kiminaze
- AdvancedParking by Kiminaze
---------------------------------------
I also plan to integrate this
- VehicleRegistration by Kiminaze

Kimi Callback is active

Maybe you can help out, or built in a support For the Scripts.
Thank you much

**Comment by Musiker15** [comment]
Look at the discord channel ap-faq. 

Replace `ESX.Game.DeleteVehicle` inside `es_extended/client/functions.lua`
```lua
ESX.Game.DeleteVehicle = function(vehicle)
    if (NetworkGetEntityIsNetworked(vehicle)) then
        TriggerServerEvent("AdvancedParking:deleteVehicle", GetVehicleNumberPlateText(vehicle), true)
        Citizen.Wait(300)
    end

    if (DoesEntityExist(vehicle)) then
        SetEntityAsMissionEntity(vehicle,  false,  true)
        DeleteVehicle(vehicle)
    end
end
```

**Comment by LimnedMoon** [comment]
This is Not the Solution. Its in the readme....and Worked well in the
past....
as long i have engine toggle and vehicle key chain These vehicles sparen
instant....

Musiker15 ***@***.***> schrieb am So., 23. Jan. 2022, 20:56:

**Comment by Musiker15** [comment]
That isn't an issue from EngineToggle.
