### ISSUE TITLE
Where to add "Make sure to add the following in every Script that spawns a Vehicle" for LukeGarages

### ISSUE THREAD

**Issue by LimnedMoon** [Musiker15/msk_enginetoggle#7]
""Make sure to add the following in every Script that spawns a Vehicle

-- Give a Key to the Player
SetVehicleNumberPlateText(vehicle, 'PLATE_TEXT')
exports["kimi_callbacks"]:Trigger("VKC:createNewKey", 'PLATE_TEXT', 1, true)
-- Remove the Key from the Player
exports["kimi_callbacks"]:Trigger("VKC:removeKey", 'PLATE_TEXT', 1)""

Where for LukeGarages ? 
Client? Config? Server? 

Which line ?

Nothin works

**Comment by Musiker15** [comment]
This work too.
```lua
local numberPlate = GetVehicleNumberPlateText(vehicle)
-- Give a Key to the Player
exports["kimi_callbacks"]:Trigger("VKC:createNewKey", numberPlate, 1, true)
-- Remove the Key from the Player
exports["kimi_callbacks"]:Trigger("VKC:removeKey", numberPlate, 1)
```
or this
```lua
-- Give a Key to the Player
SetVehicleNumberPlateText(vehicle, 'PLATE_TEXT')
exports["kimi_callbacks"]:Trigger("VKC:createNewKey", 'PLATE_TEXT', 1, true)
-- Remove the Key from the Player
exports["kimi_callbacks"]:Trigger("VKC:removeKey", 'PLATE_TEXT', 1)
```

**Comment by Musiker15** [comment]
But you have to edit your garage for your own. Ask Kiminaze in myScripts Discord for help.

**Comment by Musiker15** [comment]
You don't have to add this in any Garage. You only have to add this in for example esx_dmvschool

**Comment by LimnedMoon** [comment]
atm nothin of my tryouts worked, in kiminaze DC ive seen you alternative code, but this didnt work either. 
Aaahm, and ya, i need this to put in es:extended also ? because if i spawn a vehicle as admin via /car NAME i cant start the engine becauso no key

**Comment by Musiker15** [comment]
Yes then you have to add this in es_extended too.

For that add this:
```lua
local numberPlate = GetVehicleNumberPlateText(vehicle)
-- Give a Key to the Player
exports["kimi_callbacks"]:Trigger("VKC:createNewKey", numberPlate, 1, true)
-- Remove the Key from the Player
exports["kimi_callbacks"]:Trigger("VKC:removeKey", numberPlate, 1)
```

**Comment by LimnedMoon** [comment]
Alright- Thanks again ;)

**Comment by Marc85BPG** [comment]
Dude, sorry but where? 
client / common/funtions/modules ? 
Can you precise your Answers maybe please ?
